[package]
name = "quickhull"
version = "0.1.0"
authors = ["Trevor"]

[dependencies]
time = "0.1.35"
rand = "0.3.14"
csv = "0.14.4"
clap = "2.3.0"

[dependencies.adapton]
git = "https://github.com/cuplv/adapton.rust"
branch = "dev"
