[package]
name = "quickhull"
version = "0.1.0"
authors = ["Trevor"]

[dependencies]
time = "0.1"
rand = "0.3"
csv = "0.14.4"
clap = "2.3.0"

[dependencies.funlist]
git = "https://github.com/cuplv/funlist.rs"